/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SavedImport } from './routes/saved'
import { Route as RequestSourceImport } from './routes/request-source'
import { Route as IndexImport } from './routes/index'
import { Route as CColumnImport } from './routes/c.$column'

// Create/Update Routes

const SavedRoute = SavedImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRoute,
} as any)

const RequestSourceRoute = RequestSourceImport.update({
  id: '/request-source',
  path: '/request-source',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CColumnRoute = CColumnImport.update({
  id: '/c/$column',
  path: '/c/$column',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/request-source': {
      id: '/request-source'
      path: '/request-source'
      fullPath: '/request-source'
      preLoaderRoute: typeof RequestSourceImport
      parentRoute: typeof rootRoute
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedImport
      parentRoute: typeof rootRoute
    }
    '/c/$column': {
      id: '/c/$column'
      path: '/c/$column'
      fullPath: '/c/$column'
      preLoaderRoute: typeof CColumnImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request-source': typeof RequestSourceRoute
  '/saved': typeof SavedRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request-source': typeof RequestSourceRoute
  '/saved': typeof SavedRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/request-source': typeof RequestSourceRoute
  '/saved': typeof SavedRoute
  '/c/$column': typeof CColumnRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/request-source' | '/saved' | '/c/$column'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/request-source' | '/saved' | '/c/$column'
  id: '__root__' | '/' | '/request-source' | '/saved' | '/c/$column'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestSourceRoute: typeof RequestSourceRoute
  SavedRoute: typeof SavedRoute
  CColumnRoute: typeof CColumnRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestSourceRoute: RequestSourceRoute,
  SavedRoute: SavedRoute,
  CColumnRoute: CColumnRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/request-source",
        "/saved",
        "/c/$column"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/request-source": {
      "filePath": "request-source.tsx"
    },
    "/saved": {
      "filePath": "saved.tsx"
    },
    "/c/$column": {
      "filePath": "c.$column.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
